apiVersion: v1
kind: Namespace
metadata:
  name: inkwell
  labels:
    istio-injection: enabled
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: inkwell-monitoring
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
